// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvbfu_k19YCxfpw-ZL-XFF_zj-hUaTiE',
    appId: '1:288926534178:web:919302c697b698cc47987b',
    messagingSenderId: '288926534178',
    projectId: 'mynotesapp-9f581',
    authDomain: 'mynotesapp-9f581.firebaseapp.com',
    storageBucket: 'mynotesapp-9f581.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrEzWtifztMdLLJgTaQ6w3qBh5-1tdqk',
    appId: '1:288926534178:android:3c94e6e3a5d7352f47987b',
    messagingSenderId: '288926534178',
    projectId: 'mynotesapp-9f581',
    storageBucket: 'mynotesapp-9f581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHa4x2GXeS6iU-VB4IY_3jfwjOktNrUlo',
    appId: '1:288926534178:ios:72bfc092c3b8da0047987b',
    messagingSenderId: '288926534178',
    projectId: 'mynotesapp-9f581',
    storageBucket: 'mynotesapp-9f581.firebasestorage.app',
    iosBundleId: 'com.example.mynotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHa4x2GXeS6iU-VB4IY_3jfwjOktNrUlo',
    appId: '1:288926534178:ios:72bfc092c3b8da0047987b',
    messagingSenderId: '288926534178',
    projectId: 'mynotesapp-9f581',
    storageBucket: 'mynotesapp-9f581.firebasestorage.app',
    iosBundleId: 'com.example.mynotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyvbfu_k19YCxfpw-ZL-XFF_zj-hUaTiE',
    appId: '1:288926534178:web:bbb90a9254fd2ff147987b',
    messagingSenderId: '288926534178',
    projectId: 'mynotesapp-9f581',
    authDomain: 'mynotesapp-9f581.firebaseapp.com',
    storageBucket: 'mynotesapp-9f581.firebasestorage.app',
  );
}
